apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: rust-ci-run
spec:
  pipelineRef:
    name: rust-ci-pipeline
  params:
    - name: git-url
      value: "https://github.com/yurikrupnik/first-rust-app
    - name: git-revision
      value: "master"
    - name: build-profile
      value: "debug"
    - name: run-clippy
      value: "true"
    - name: create-binary
      value: "false"
  workspaces:
    - name: source-code
      persistentVolumeClaim:
        claimName: rust-source-pvc
    - name: cargo-cache
      persistentVolumeClaim:
        claimName: cargo-cache-pvc
